### ISSUE TITLE
browser bundle is corrupted after recent refactor released as v1.3.0

### ISSUE THREAD

**Issue by bhovhannes** [Workfront/workfront-api#16]

**Comment by bhovhannes** [comment]
Stack trace:

՝՝՝
Error: Cannot find module 'workfront-api-constants/dist/umd/constants' 
at Function.Module._resolveFilename (module.js:326:15) 
at Function.Module._load (module.js:277:25) 
at Module.require (module.js:354:17) 
at require (internal/module.js:12:17) 
at Object.<anonymous> (/etc/attask-devops/workspace/1/node_modules/@wf-qa/acceptance-test/node_modules/workfront-api/src/plugins/get.js:22:23) 
at Module._compile (module.js:398:26) 
at Object.Module._extensions..js (module.js:405:10) 
at Module.load (module.js:344:32) 
at Function.Module._load (module.js:301:12) 
at Module.require (module.js:354:17)

**Comment by bhovhannes** [comment]
The issue was because `workfront-api-constants` has been incorrectly added as devDependency and was not affecting browser bundle but instead Node version of workfront-api.

[Release 1.3.4](https://github.com/Workfront/workfront-api/releases/tag/v1.3.4) fixes this issue.
