### ISSUE TITLE
predecessorExpression from project tasks causes crash

### ISSUE THREAD

**Issue by ogtony** [Workfront/workfront-api#641]
The following code will cause a crash when run:
```
instance.search('proj', {
      'name': project_name,
      'fields': 'tasks:predecessorExpression'
    })
```
The error is reported as
```
FetchError: invalid json response body at https://[redacted subdomain].my.workfront.com/attask/api-internal/proj/search?name=nameyousearchedfor&fields=tasks%3ApredecessorExpression reason: Unexpected end of JSON input
    at path\to\project\node_modules\node-fetch\lib\body.js:48:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'FetchError',
  message: 'invalid json response body at https://[redacted subdomain].my.workfront.com/attask/api-internal/proj/search?name=nameyousearchedfor&fields=tasks%3ApredecessorExpression reason: Unexpected end of JSON input',
  type: 'invalid-json'
}
```
Digging in a little, the json returned from the endpoint is incomplete: 
```
{"data":[
```

**Comment by citizensas** [comment]
I can give an answer as `workfront-api` contributor.
Your query is slightly wrong. Here's what I believe you want to request.
```js
instance.search('proj', { 'name': project_name' }, 'tasks:predecessorExpression')
```
`fields` which you want to retrieve are passed through the 3rd parameter of `.search` method.

Let me know if that helped.

**Comment by bhovhannes** [comment]
Closing this because of no activity. Will reopen if needed.
